# Generated by Django 2.2.17 on 2021-04-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate_the_game_app', '0003_auto_20210330_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('comment', models.CharField(max_length=2000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_the_game_app.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate_the_game_app.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
